services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - PORT=8080
      - REDIS_URL=redis://redis:6379
    volumes:
      - .:/app
    command: npm run dev
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
